/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "fqzxdcbjhgpkagalvgqt"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxenhkY2JqaGdwa2FnYWx2Z3F0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk4NTAxNzAsImV4cCI6MjA4NTQyNjE3MH0.8iKkDn4qqFUBT2ApPcgKNql__pI7hVsdebeCBeutyG4"